import Image from 'next/image';
import { articles } from '@/lib/content';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';

type Section = { heading: string; paragraphs: string[] };
type Source = { label: string; href: string };
const bodies: Record<string, { sections: Section[]; sources: Source[] }> = {
  'hugging-face-hack-lessons': {
    sections: [
      { heading: 'What happened', paragraphs: ['In May 2024, Hugging Face said its security team detected unauthorised access to its Spaces platform. The company warned that a subset of Spaces secrets might have been accessed without authorisation, revoked affected tokens and advised users to refresh keys or tokens and move to fine-grained access tokens.', 'The useful lesson is broader than one platform or incident. AI products combine model hosts, source repositories, notebooks, data stores, deployment services and external APIs. A secret exposed at any one boundary can provide a route into several others. Model security is therefore also ordinary cloud, software supply-chain and identity security.'] },
      { heading: 'Treat every token as a capability', paragraphs: ['A token should have the narrowest permission and shortest useful life. Development, test and production environments should use separate credentials. A model demo should never inherit broad access simply because it is convenient to copy an existing key.', 'Inventory where secrets are created, stored and consumed. Use a managed secret store, prevent values appearing in logs and scan repositories before every merge. Rotation must be rehearsed, not merely documented. If a key is compromised, the team should know which systems depend on it and how to replace it without improvisation.'] },
      { heading: 'Secure the AI supply chain', paragraphs: ['Models and datasets are executable inputs to a business system. Record their origin, version, licence and integrity. Review third-party code used to load or transform them. Isolate evaluation of unfamiliar artefacts and avoid formats that can execute arbitrary code when a safer format is available.', 'The NCSC secure AI development guidance recommends considering security across design, development, deployment, and operation and maintenance. That lifecycle view matters because a safe launch can become unsafe when permissions drift, dependencies age or monitoring stops.'] },
      { heading: 'An incident-ready checklist', paragraphs: ['Know the owner of every AI service. Enable useful audit logs. Alert on unusual token use, new deployment locations and large data transfers. Prepare a contact route for suppliers and a decision process for disabling an affected feature. Finally, test the response with a realistic tabletop exercise.', 'The goal is not to avoid useful platforms. It is to make platform choice reversible and incidents containable. Strong boundaries let teams innovate with more confidence because one compromised component cannot quietly become a compromise of the whole business.'] }
    ],
    sources: [
      { label: 'Hugging Face, Spaces Platform Security Update', href: 'https://huggingface.co/blog/space-secrets-disclosure' },
      { label: 'NCSC and partners, Guidelines for Secure AI System Development', href: 'https://www.ncsc.gov.uk/collection/guidelines-secure-ai-system-development' },
      { label: 'NIST, Secure Software Development Framework', href: 'https://csrc.nist.gov/Projects/ssdf' }
    ]
  },
  'business-ai-risk-register': {
    sections: [
      { heading: 'Risk belongs to a use case', paragraphs: ['A board cannot govern AI as one abstract item. A meeting summariser, pricing recommendation and customer-facing legal answer have different data, impact and failure modes. Start the register with a named use case, an operational owner and the people who could be affected.', 'Describe what the system receives, produces and is allowed to do. Record whether output is advisory or automatic, how a person intervenes and what evidence is retained. This turns a general concern into a system that can be tested.'] },
      { heading: 'Five risk lenses', paragraphs: ['Review data and privacy, security, accuracy, fairness and operational resilience. For each lens, describe a plausible failure and its consequence. A risk statement should be concrete: confidential client text reaches an unapproved provider, rather than AI may create privacy issues.', 'Score likelihood and impact only after the scenario is clear. Then name current controls, missing controls, an owner and a review date. Controls might include data minimisation, retrieval permissions, evaluation sets, content filters, human approval, supplier terms, fallback procedures and logging.'] },
      { heading: 'Security needs its own threat model', paragraphs: ['AI adds threats including prompt injection, model or data poisoning, sensitive information disclosure and excessive agency. It also inherits familiar threats such as stolen credentials, vulnerable dependencies and poor access control. Treating every problem as uniquely AI can distract from basic safeguards.', 'Map trust boundaries around users, models, tools and data stores. Assume content retrieved from outside the organisation can contain hostile instructions. Limit tool permissions, validate outputs before actions and prevent the model from deciding its own security boundary.'] },
      { heading: 'Governance should accelerate good work', paragraphs: ['Use tiers so low-impact internal experiments move quickly while consequential systems receive deeper assurance. Revisit the register when the model, data, action scope or supplier changes. Monitor live outcomes because pre-launch testing cannot represent every situation.', 'A useful register is short enough to use and specific enough to change a decision. It gives leaders a portfolio view while giving delivery teams a clear path to approval.'] }
    ],
    sources: [
      { label: 'NIST, AI Risk Management Framework', href: 'https://www.nist.gov/itl/ai-risk-management-framework' },
      { label: 'ICO, Guidance on AI and Data Protection', href: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/artificial-intelligence/' },
      { label: 'UK Government, Generative AI Framework for HMG', href: 'https://www.gov.uk/government/publications/generative-ai-framework-for-hmg' }
    ]
  },
  'b2b-marketing-pipelines': {
    sections: [
      { heading: 'The promise: better context at useful scale', paragraphs: ['AI can consolidate account signals, summarise public information, draft segment hypotheses and help a seller prepare for a conversation. Used well, it returns research time to people and makes outreach more relevant to the buyer’s actual situation.', 'A pipeline can also connect campaign response with CRM history and product usage, helping teams decide which action is useful next. The commercial benefit comes from better prioritisation and context, not from sending the maximum possible volume.'] },
      { heading: 'The problem: synthetic sameness', paragraphs: ['When every competitor automates surface-level personalisation, inboxes fill with messages that mention a recent post but demonstrate no real understanding. Response rates fall, brands look interchangeable and sales teams inherit low-quality conversations.', 'Generation is cheap, but attention and reputation are scarce. Require a genuine reason to contact each account. Let AI prepare evidence and options while a person owns the proposition, accuracy and timing. A smaller list with a strong hypothesis often outperforms a large list decorated with generated sentences.'] },
      { heading: 'Build compliance into the data path', paragraphs: ['Map the source and lawful use of personal data before enrichment. Separate corporate account research from information about an identifiable person. Respect suppression lists and channel rules, and ensure objections propagate through every connected tool.', 'The ICO’s direct marketing guidance makes clear that UK GDPR and PECR both matter. Buying or scraping data does not remove the sender’s responsibilities. The pipeline should record source, purpose, consent or legitimate-interest reasoning and the most recent preference.'] },
      { heading: 'A stronger B2B operating model', paragraphs: ['Use AI for research compression, segmentation support, call preparation, content variation and post-conversation summaries. Keep account selection, claims, sensitive inference and final outreach accountable to a person. Measure qualified conversations, progression and trust signals rather than messages generated.', 'Custom pipelines win because they encode the firm’s ideal customer profile, evidence, vocabulary and hand-off rules. A generic writing tool can produce copy. A specialised commercial system helps the whole team make better decisions.'] }
    ],
    sources: [
      { label: 'ICO, Direct Marketing Guidance', href: 'https://ico.org.uk/for-organisations/direct-marketing-and-privacy-and-electronic-communications/' },
      { label: 'CMA, Online Choice Architecture', href: 'https://www.gov.uk/government/publications/online-choice-architecture-how-digital-design-can-harm-competition-and-consumers' },
      { label: 'UK Government, AI Activity in UK Businesses', href: 'https://www.gov.uk/government/publications/ai-activity-in-uk-businesses' }
    ]
  },
  'secure-legal-llms': {
    sections: [
      { heading: 'Legal work needs bounded intelligence', paragraphs: ['A general chatbot can help explore language, but legal work depends on authority, matter context, confidentiality and professional judgement. The useful question is not whether a model sounds fluent. It is whether the complete system can show what it used, what it was allowed to see and where uncertainty remains.', 'A legal AI workspace should begin at the matter boundary. Access follows the document management system, not a shared index. Retrieval respects ethical walls and client terms. Outputs link back to passages so a qualified person can verify them.'] },
      { heading: 'Private does not automatically mean safe', paragraphs: ['Private hosting can reduce some disclosure risks, but it also creates patching, monitoring and capacity responsibilities. A managed model with contractual protections may be safer than a poorly operated private deployment. Architecture should follow the threat model and client obligation rather than a slogan.', 'Minimise prompts and retention, encrypt traffic and stored indexes, and separate telemetry from client content. Test whether users can retrieve information from matters they cannot otherwise access. Review subprocessors and understand whether submitted data is used for provider training.'] },
      { heading: 'Agents require explicit authority', paragraphs: ['A services agent might assemble a chronology, compare clauses, prepare a due diligence table or draft a client update. Each action should use approved sources and stop before a consequential external step. Sending advice, filing, changing a matter record or committing a deadline requires clear human authority.', 'Evaluation should include citation accuracy, omission, privilege boundaries, conflicting documents and adversarial instructions embedded in files. Record both model output and reviewer correction so quality can improve without silently learning from unapproved material.'] },
      { heading: 'Why specialised systems outperform generic chat', paragraphs: ['The strongest solution is usually not a newly trained foundation model. It is a custom-built specialised system using an appropriate model inside matter-specific retrieval, permissions, templates, checks and audit. That design captures the firm’s working method while keeping the model replaceable.', 'Specialisation produces a narrower task, stronger evaluation and clearer accountability. It also improves adoption because the interface fits the lawyer’s workflow instead of asking every user to become a prompt engineer.'] }
    ],
    sources: [
      { label: 'ICO, Guidance on AI and Data Protection', href: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/artificial-intelligence/' },
      { label: 'NIST, Generative AI Profile', href: 'https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence' },
      { label: 'UK Government, Generative AI Framework for HMG', href: 'https://www.gov.uk/government/publications/generative-ai-framework-for-hmg' }
    ]
  },
  'industry-specific-ai-strategies': {
    sections: [
      { heading: 'Strategy starts with industry reality', paragraphs: ['An AI strategy copied from another sector will miss the language, evidence and consequences that make work distinctive. In legal services, provenance and privilege dominate. In cold-chain operations, sensor reliability and response time matter. In marine services, fragmented customer and asset information may be the constraint.', 'Begin with the operating model: where margin is created, where risk concentrates and which decisions repeat. Then select the smallest system that improves one of those points. Technology choice follows the work.'] },
      { heading: 'Different sectors, different patterns', paragraphs: ['Professional services benefit from secure knowledge retrieval, document workflows and review support. Industrial and logistics teams often gain more from exception detection, maintenance context and shift reporting. Property businesses need pipeline coordination across documents, parties and deadlines. B2B firms need account intelligence linked to disciplined human outreach.', 'The common pattern is integration around trusted evidence. The model interprets variation, while conventional software controls identity, state, calculations and action. Human specialists remain responsible where context or consequence demands it.'] },
      { heading: 'Generic platforms have a useful role', paragraphs: ['General tools are fast to trial, familiar and increasingly capable. They are appropriate for low-risk drafting, learning and individual productivity. Their weakness appears when a business needs consistent process, domain permissions, evidence, integration and measurable outcomes.', 'Training a proprietary model is rarely the first answer for an SME. It is expensive and can freeze capability at the wrong layer. Customisation more often means a specialised application that combines selected models with private retrieval, business rules, tools, evaluation and a domain-specific interface.'] },
      { heading: 'Why custom-built specialised systems win', paragraphs: ['A specialised system narrows the problem enough to test it properly. It can use industry vocabulary, surface the right evidence, enforce permissions and fit existing accountability. It also keeps commercial knowledge in the workflow rather than scattering it across personal chat histories.', 'The result is not AI for its own sake. It is a dependable operating capability that improves with use. Build one valuable pattern, measure it, then reuse its security, data and evaluation foundations across the next industry-specific workflow.'] }
    ],
    sources: [
      { label: 'UK Government, AI Activity in UK Businesses', href: 'https://www.gov.uk/government/publications/ai-activity-in-uk-businesses' },
      { label: 'NIST, AI Risk Management Framework', href: 'https://www.nist.gov/itl/ai-risk-management-framework' },
      { label: 'NCSC and partners, Guidelines for Secure AI System Development', href: 'https://www.ncsc.gov.uk/collection/guidelines-secure-ai-system-development' }
    ]
  },
  'open-weight-price-war': {
    sections: [
      { heading: 'Capability is becoming cheaper', paragraphs: ['The economics of artificial intelligence are shifting quickly. Open-weight model families now compete across coding, reasoning, extraction and multilingual work. The practical result is not simply a busier leaderboard. It is a lower cost of testing useful business applications.', 'Stanford’s 2025 AI Index reports a steep fall in the cost of querying a model at the capability level associated with GPT-3.5. That change makes classification, document processing, retrieval and structured drafting realistic experiments for firms that could not justify them two years ago.'] },
      { heading: 'The model is only one line in the budget', paragraphs: ['Cheap inference does not create a business case by itself. Reliable systems still need process design, clean access to information, security controls, evaluation and training. For many SMEs, the most valuable effect of lower model prices is the freedom to spend more of the budget on those lasting foundations.', 'A sensible pilot starts with a bounded task and a baseline. Record the current time, error rate and cost. Build a representative evaluation set before comparing providers. A model that looks inexpensive per token can become costly if its errors create repeated review or rework.'] },
      { heading: 'Design for choice', paragraphs: ['Leaders should avoid tying an operating process permanently to one provider. Keep prompts, retrieval logic, evaluation cases and business rules outside the model where practical. This makes it easier to compare quality, latency, hosting and price as the market changes.', 'Open weights can provide greater deployment control, but control creates responsibility. Teams must understand licensing, model provenance, data handling and the operational burden of hosting. NIST’s AI Risk Management Framework provides a useful structure for governing those decisions without treating every use case as equally risky.'] },
      { heading: 'A practical next step', paragraphs: ['Choose one high-volume task where output can be checked quickly. Test two model families against the same examples, including awkward edge cases. Compare total workflow cost rather than headline token price. The winning design is the one that produces dependable value and remains easy to change.'] }
    ],
    sources: [
      { label: 'Stanford HAI, 2025 AI Index Report', href: 'https://hai.stanford.edu/ai-index/2025-ai-index-report' },
      { label: 'NIST, AI Risk Management Framework', href: 'https://www.nist.gov/itl/ai-risk-management-framework' },
      { label: 'UK Government, AI Activity in UK Businesses', href: 'https://www.gov.uk/government/publications/ai-activity-in-uk-businesses' }
    ]
  },
  'automation-before-agents': {
    sections: [
      { heading: 'Start with the work, not the agent', paragraphs: ['AI agents are often presented as ready-made digital employees. In practice, reliability depends on the process around them. A vague workflow produces vague automation, while an unstable process gives an agent more ways to fail.', 'Follow a real item of work from arrival to completion. Note where information enters, which decisions need judgement, what exceptions stop progress and who is accountable. This map reveals whether the constraint is interpretation, missing data, unclear ownership or an ordinary integration problem.'] },
      { heading: 'Use the least complex reliable tool', paragraphs: ['Conventional automation remains better for deterministic steps such as moving validated fields, applying fixed calculations or sending a known notification. Use AI where language, variation or interpretation makes it useful. Combining both approaches is usually more dependable than asking one agent to improvise the whole process.', 'Separate actions by consequence. Drafting a summary can tolerate review. Releasing a payment, changing a customer record or sending regulated advice requires explicit approval and a durable audit trail. The system should make uncertainty visible rather than concealing it behind confident prose.'] },
      { heading: 'Build an evaluation loop', paragraphs: ['Create examples of normal work, edge cases and known failures. Define what a good result means before launch. Track task completion, corrections, time saved and exceptions that reach a person. A small evaluation set used every week is more useful than a one-off demonstration.', 'NIST describes trustworthy AI through characteristics including validity, safety, security, transparency and accountability. Those qualities become practical when each automated step has an owner, a test and a clear route for intervention.'] },
      { heading: 'Earn autonomy gradually', paragraphs: ['Begin with recommendation or drafting, then expand authority only when evidence supports it. The best first system is rarely the most autonomous. It is the one the team can understand, trust and improve without depending on a vendor demonstration.'] }
    ],
    sources: [
      { label: 'NIST, AI Risk Management Framework', href: 'https://www.nist.gov/itl/ai-risk-management-framework' },
      { label: 'NIST, Generative AI Profile', href: 'https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence' },
      { label: 'UK Government, Introduction to AI Assurance', href: 'https://www.gov.uk/government/publications/introduction-to-ai-assurance' }
    ]
  },
  'cold-chain-collaboration': {
    sections: [
      { heading: 'From readings to decisions', paragraphs: ['Quiet Gears has begun a collaboration focused on information flow in temperature-controlled operations. Cold-chain environments generate a steady stream of readings, checks, maintenance notes and exceptions. The challenge is ensuring that important change produces a timely, accountable response.', 'Temperature data has value only when teams can interpret it in context. A short excursion during loading may require a different response from a persistent rise in a sealed unit. Useful software brings readings, equipment state, operating thresholds and human notes into one coherent timeline.'] },
      { heading: 'Design around exceptions', paragraphs: ['Our early work is exploring an exception-led workflow. Instead of asking staff to repeatedly assemble routine reports, the system can identify unusual activity, collect relevant context and prepare a concise summary for review. People remain responsible for decisions while spending more time on situations that need their expertise.', 'The Food Standards Agency advises food businesses to check and record temperatures as part of food safety management. Digital records can make this evidence easier to retrieve, but the design must reflect the operator’s actual checks, escalation routes and retention needs.'] },
      { heading: 'Infrastructure matters', paragraphs: ['Monitoring cannot compensate for poor sensors, unreliable connectivity or unclear maintenance. Discovery therefore includes the physical estate: sensor placement, calibration, gateways, network gaps and the behaviour of each refrigeration asset. The software layer should report missing or implausible data rather than quietly treating it as normal.', 'Security also matters when operational equipment becomes connected. Access should be limited, changes should be logged and monitoring services should be separated from direct equipment control unless a carefully assessed need exists.'] },
      { heading: 'Small, measurable releases', paragraphs: ['The engagement reflects our wider approach: understand operational reality first, establish a trustworthy data path, then deliver the smallest useful combination of software, automation and AI. Initial measures include reporting time, alert quality, response time and the proportion of exceptions resolved with complete evidence.'] }
    ],
    sources: [
      { label: 'Food Standards Agency, Chilling Food Correctly', href: 'https://www.food.gov.uk/business-guidance/chilling-food-correctly-in-your-business' },
      { label: 'UK Government, Temperature Control Legislation Guidance', href: 'https://www.legislation.gov.uk/uksi/2006/14/contents/made' },
      { label: 'NCSC, Connected Places Cyber Security Principles', href: 'https://www.ncsc.gov.uk/collection/connected-places-security-principles' }
    ]
  },
  'small-teams-ai-advantage': {
    sections: [
      { heading: 'Speed comes from proximity', paragraphs: ['Large organisations may have more capital and data, but smaller firms possess advantages that matter when adopting AI: short decision lines, less legacy infrastructure and close knowledge of the customer. A specialist team can observe a problem, test a change and hear the consequences quickly.', 'That proximity reduces the translation loss between leadership, operations and delivery. The person who understands the exception can sit beside the person building the system. Decisions that might require several committees in a large organisation can be tested in days with the right safeguards.'] },
      { heading: 'Focus is the constraint', paragraphs: ['Trying tools across every department creates activity without capability. Choose one valuable workflow, define the desired operational change and give a small cross-functional group authority to deliver it. The use case should be frequent enough to measure and bounded enough to understand.', 'The UK Government’s research into AI activity in UK businesses identifies skills, cost and uncertainty among adoption barriers. A focused first project helps address all three by linking learning to a real commercial outcome rather than abstract training.'] },
      { heading: 'Create foundations that compound', paragraphs: ['A good pilot leaves more than an application. It creates clearer data ownership, a reusable evaluation method, a practical view of risk and colleagues who understand how to improve an AI-enabled workflow. Those capabilities lower the cost of the next project.', 'Document decisions and keep interfaces replaceable. Assign an operational owner, not only a technical owner. Review whether the system still saves time and produces acceptable outcomes after the novelty has faded.'] },
      { heading: 'Learn faster, responsibly', paragraphs: ['Small teams do not need to imitate an enterprise transformation programme. They need a repeatable rhythm: select, baseline, test, review and expand. Responsible adoption is not a brake on speed. Clear boundaries and evidence are what make confident iteration possible.'] }
    ],
    sources: [
      { label: 'UK Government, AI Activity in UK Businesses', href: 'https://www.gov.uk/government/publications/ai-activity-in-uk-businesses' },
      { label: 'Office for National Statistics, Business Insights and Impact on the UK Economy', href: 'https://www.ons.gov.uk/businessindustryandtrade/business/businessservices/bulletins/businessinsightsandimpactontheukeconomy/latest' },
      { label: 'NIST, AI Risk Management Framework', href: 'https://www.nist.gov/itl/ai-risk-management-framework' }
    ]
  }
};

export function generateStaticParams() { return articles.map(article => ({ slug: article.slug })); }
export default async function Article({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const article = articles.find(item => item.slug === slug);
  const body = bodies[slug];
  if (!article || !body) notFound();
  return <article className="article-detail"><Link className="back" href="/news"><ArrowLeft size={16}/> All news</Link><span className="kicker">{article.tag} · {article.date} · {article.read}</span><h1>{article.title}</h1><p className="lede">{article.intro}</p><div className="article-hero-image"><Image src={article.image} alt="" fill priority sizes="(max-width: 1000px) 100vw, 860px"/><span>{article.artLabel}</span></div><div className="prose">{body.sections.map(section => <section key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</section>)}<aside className="references"><h2>References and further reading</h2><ol>{body.sources.map(source => <li key={source.href}><a href={source.href} target="_blank" rel="noreferrer">{source.label} <ArrowUpRight size={14}/></a></li>)}</ol></aside></div></article>;
}
