export const cases=[
 {slug:'yacht-operations',image:'/images/case-yacht.svg',sector:'Marine',title:'A calmer operating system for a growing yacht business',summary:'Unifying fragmented enquiries, customer records and operational tasks into one clear workflow.',status:'In progress',challenge:'A specialist sailing business had strong demand, but customer information and operational work were spread across inboxes, documents and individual knowledge.',work:'We are designing a tailored operational platform that brings customer journeys, project details and next actions into one dependable view.',result:'Work is under way. The early system design has established a clear source of truth and a foundation for thoughtful automation.'},
 {slug:'cold-chain',image:'/images/case-cold-chain.svg',sector:'Cold storage',title:'Turning temperature data into timely action',summary:'A focused monitoring and reporting system designed to reduce manual oversight across cold-chain operations.',status:'Illustrative',challenge:'Operational teams were spending too much time consolidating equipment data and preparing routine status reports.',work:'We designed an exception-led workflow that gathers readings, surfaces unusual activity and drafts clear operational summaries for human approval.',result:'The illustrative solution shows how teams can move from scheduled checking to focused intervention, without losing human oversight.'},
 {slug:'property-pipeline',image:'/images/case-property.svg',sector:'Real estate',title:'Giving property teams one view of the pipeline',summary:'Connecting enquiries, documents and follow-ups to make complex transactions easier to move forward.',status:'Illustrative',challenge:'A growing property firm relied on disconnected systems, creating duplicate entry and inconsistent follow-up across a busy deal pipeline.',work:'We mapped the journey from initial enquiry to completion and designed a lightweight application that coordinates information, prompts and responsibilities.',result:'The concept reduces the administrative drag around each transaction and gives leadership a clearer, more current view of progress.'}
];
export const articles=[
 {slug:'hugging-face-hack-lessons',image:'/images/news-security.svg',artLabel:'Platform security',date:'14 Aug 2026',read:'9 min read',tag:'AI security',title:'What the Hugging Face Spaces breach teaches every AI team',intro:'A platform incident is a reminder that model security includes tokens, secrets, dependencies and the people operating them.'},
 {slug:'open-weight-price-war',image:'/images/code-waterfall.svg',artLabel:'Model economics',date:'12 Aug 2026',read:'9 min read',tag:'AI market',title:'The open-weight price war is good news for British SMEs',intro:'Chinese model makers are compressing the cost of capable AI. The strategic question is no longer whether SMEs can afford intelligence, but where it can earn a return.'},
 {slug:'business-ai-risk-register',image:'/images/news-security.svg',artLabel:'Risk architecture',date:'05 Aug 2026',read:'10 min read',tag:'Risk & security',title:'The practical AI risk register every business needs',intro:'AI risk becomes manageable when leaders connect each use case to data, actions, owners, controls and evidence.'},
 {slug:'automation-before-agents',image:'/images/case-property.svg',artLabel:'Workflow sketch',date:'28 Jul 2026',read:'8 min read',tag:'Practical AI',title:'Before you buy an AI agent, fix the workflow',intro:'An agent cannot rescue a process nobody understands. Start with the hand-offs, decisions and exceptions that define the work.'},
 {slug:'b2b-marketing-pipelines',image:'/images/news-marketing.svg',artLabel:'Marketing pipeline',date:'21 Jul 2026',read:'9 min read',tag:'B2B strategy',title:'AI marketing pipelines: reach, relevance and the risk of synthetic noise',intro:'AI can make B2B research and personalisation sharper, but unchecked volume damages trust and weakens the commercial signal.'},
 {slug:'cold-chain-collaboration',image:'/images/case-cold-chain.svg',artLabel:'Cooling infrastructure',date:'09 Jul 2026',read:'8 min read',tag:'Client news',title:'Quiet Gears begins cold-chain systems collaboration',intro:'We are working with a specialist operator to explore better data flow, reporting and exception management across temperature-controlled operations.'},
 {slug:'secure-legal-llms',image:'/images/news-legal.svg',artLabel:'Private legal workspace',date:'02 Jul 2026',read:'10 min read',tag:'Professional services',title:'Secure legal AI needs more than a general-purpose chatbot',intro:'For legal teams, the strongest AI is bounded by matter, permission and precedent, with citations and review designed into every answer.'},
 {slug:'small-teams-ai-advantage',image:'/images/case-yacht.svg',artLabel:'Small team, clear course',date:'18 Jun 2026',read:'7 min read',tag:'Insight',title:'Why smaller teams may hold the AI advantage',intro:'Less legacy, shorter decision lines and closer customer knowledge give SMEs a powerful starting point; if they focus.'},
 {slug:'industry-specific-ai-strategies',image:'/images/news-industries.svg',artLabel:'Industry strategy map',date:'05 Jun 2026',read:'11 min read',tag:'AI strategy',title:'One AI strategy does not fit every industry',intro:'The winning pattern is not a generic model everywhere. It is a specialised system shaped around each industry’s language, evidence and consequences.'}
];
