export type EditorialSection = { heading: string; paragraphs: string[] };

export type NewsEditorial = {
  title: string;
  standfirst: string;
  thesis: string;
  takeaways: string[];
  sections: EditorialSection[];
};

export const newsEditorial: Record<string, NewsEditorial> = {
  'ai-integration-gap': {
    title: 'The AI integration gap is now a management problem',
    standfirst: 'Access to artificial intelligence has spread faster than the operating discipline required to make it useful. The next phase will be decided by workflow design, data ownership and management attention rather than another round of software licences.',
    thesis: 'The competitive divide is shifting from who can obtain an AI tool to who can connect it to a material workflow, govern its decisions and improve it with evidence.',
    takeaways: [
      'Adoption statistics reveal interest, but say little about operational value.',
      'Integration requires decisions about data, authority, exceptions and ownership.',
      'A narrow workflow with a measurable outcome is a better starting point than a broad tool rollout.',
    ],
    sections: [
      { heading: 'Adoption is a noisy measure', paragraphs: ['British surveys produce markedly different estimates of business AI use. The UK Business Data Survey reports use among firms handling digitised data, while separate government research measures adoption across the wider business population. The figures are not contradictory. They describe different populations and different thresholds for what counts as use.', 'This distinction matters because casual use and operating integration are economically different. An employee may use a general assistant to research a topic or improve a draft without changing how the organisation handles a customer, approves a decision or closes a transaction. Licence counts capture activity. They do not reveal whether work has become faster, safer or more profitable.'] },
      { heading: 'The difficult work begins after access', paragraphs: ['Only a minority of AI-using businesses report integration with existing systems. The gap is easy to explain. A production workflow needs authorised data, stable inputs, permissions, failure handling, evaluation and somebody accountable when the result is wrong. None of these arrives with the model.', 'The technical connector is often the least interesting part. The harder questions concern the operating model. Which record is authoritative? Which output may be used without review? What happens when confidence is low? Who owns an exception that crosses departmental boundaries? These decisions determine whether AI becomes infrastructure or remains an individual convenience.'] },
      { heading: 'Workflow design is the real strategy', paragraphs: ['The most useful starting point is a decision or handoff with visible economic consequence. Leaders should follow representative work from input to accepted outcome, recording delays, repeated effort, missing information and judgement. That exercise usually reveals a mixture of ordinary automation, process repair and a smaller role for AI.', 'This is a strength, not a disappointment. Deterministic software is better for fixed rules and validated data movement. AI earns its place where language or variation defeats simpler methods. A combined system is easier to explain and control than a general assistant expected to infer the entire process.'] },
      { heading: 'Integration should expose uncertainty', paragraphs: ['An AI system is not well governed merely because it displays a confidence score. Uncertainty needs an operational consequence. A weak result may require more evidence, a different reviewer or a pause in the process. If no queue, owner or service expectation exists, the score is decorative.', 'The same principle applies to data. Generated conclusions should preserve the source records that shaped them. Reviewers need to see whether the system relied on an approved document, an outdated field or an inference. Traceability turns disagreement into useful diagnostic evidence rather than an argument about the model.'] },
      { heading: 'Boards should ask about outcomes, not access', paragraphs: ['The relevant measures are cycle time, first-time quality, rework, exception demand and total operating effort. Adoption belongs in the scorecard as a leading indicator, but it is not the result. A widely used tool can still produce little value if it sits beside the workflow or creates additional checking.', 'A modest model connected to reliable records and a clear decision process may outperform a more capable model used informally. Management should therefore treat AI integration as operating-model investment. It requires a bounded objective, named owners and a willingness to redesign the work around evidence.'] },
    ],
  },
  'open-weight-price-war': {
    title: 'Cheaper AI models will not make implementation cheap',
    standfirst: 'The price of machine intelligence is falling quickly, widening the range of viable experiments. But inference is only one line in the cost of dependable automation. Review, integration and operational control will decide which apparent bargains create value.',
    thesis: 'Lower model prices increase strategic choice, but the winning architecture will minimise the cost of accepted work rather than the cost of generating an answer.',
    takeaways: [
      'Falling inference costs make disciplined comparison more valuable.',
      'Human review and exception handling can outweigh the model bill.',
      'Portability depends on evaluation, data and rules remaining outside the model.',
    ],
    sections: [
      { heading: 'Intelligence is becoming a cheaper input', paragraphs: ['The long-run direction of model economics is clear. Capability that once required an expensive frontier service is increasingly available through smaller commercial models and open-weight alternatives. This creates useful option value for smaller firms. More tasks can be tested before a large contract or platform decision is made.', 'Yet a falling input price does not guarantee a falling process cost. A document may be inexpensive to classify and still costly to complete if the result needs repeated review. Management should resist equating the model invoice with the economics of the service built around it.'] },
      { heading: 'The unit that matters is an accepted task', paragraphs: ['A realistic cost model includes infrastructure, retrieval, monitoring, review, exceptions, support and the effort required when prompts or models change. These costs behave differently. Inference tends to scale with volume. Specialist review may scale with error and consequence. Integration and control create a substantial fixed cost.', 'The useful denominator is therefore an accepted business task. This exposes false economies. A model that costs half as much but doubles correction effort is not cheaper. Nor is an apparently accurate model economical if its rare failures require an expensive control process.'] },
      { heading: 'Open weights exchange supplier cost for operating responsibility', paragraphs: ['Open-weight deployment can improve control over data location, latency and model choice. It can also create new duties involving licensing, patching, capacity, monitoring and security. For many SMEs, these obligations are material because the people able to manage them are scarce.', 'The decision should begin with a constraint. If local deployment is needed to meet a data boundary or service requirement, the additional control may justify the burden. If the only argument is avoidance of a usage fee, a managed service may remain the more economical option once operational labour is counted.'] },
      { heading: 'Portability has to be designed', paragraphs: ['Providers differ in interfaces, tool use, safety behaviour and supporting services. Switching is easy only when the application keeps its business rules, retrieval logic, schemas and evaluations outside the model. Otherwise, proprietary features quietly become part of the operating process.', 'A common adapter is useful, but the evaluation set is more important. It defines what good performance means on representative work. Without it, a change of model is a fresh act of faith rather than a controlled release. Portability is the ability to compare and change with evidence.'] },
      { heading: 'Price competition rewards disciplined buyers', paragraphs: ['Falling prices give buyers leverage. Firms can benchmark several candidates, negotiate shorter commitments and reserve specialist models for tasks where capability produces an observable return. The savings should fund stronger data, evaluation and workflow design rather than a larger volume of ungoverned output.', 'The likely winners will not be those that select one permanent model. They will build an operating system capable of changing models without changing the business process each time. In a volatile market, architectural discipline is a commercial asset.'] },
    ],
  },
  'automation-before-agents': {
    title: 'Before hiring an AI agent, repair the workflow',
    standfirst: 'Agent demonstrations make complicated work appear smooth. Real organisations contain missing information, conflicting policies and awkward exceptions. Autonomy amplifies those conditions unless the underlying process is made explicit first.',
    thesis: 'An agent should inherit a well-defined operating system, not be asked to invent one while handling live work.',
    takeaways: [
      'Process ambiguity becomes automation instability.',
      'Rules and AI should be combined according to the nature of each decision.',
      'Authority should expand only after representative evidence supports it.',
    ],
    sections: [
      { heading: 'The demonstration is not the process', paragraphs: ['A polished agent demonstration compresses work into a prompt, a plan and a successful sequence of actions. Production work is less obliging. Inputs arrive incomplete, policies collide and customers change their minds. Employees resolve these conditions through judgement and informal coordination that the process map may never have recorded.', 'Automating the demonstration rather than the work creates a system that appears capable until the first consequential exception. The correct starting point is observation. Follow real cases, including failures, and record states, evidence, decisions, wait time and ownership.'] },
      { heading: 'Ordinary automation remains underrated', paragraphs: ['Many tasks presented as opportunities for agency are better solved with forms, validation, rules and integrations. Fixed calculations should be deterministic. Required fields should be checked before a model sees them. Known notifications do not need a planning agent.', 'AI is valuable where language, ambiguity or variation creates a real advantage. Combining bounded AI with conventional software is usually stronger than giving a general agent broad responsibility. The rules provide stability, while the model handles the part that genuinely requires interpretation.'] },
      { heading: 'Authority is a design decision', paragraphs: ['Drafting an internal summary, recommending a route and releasing a payment are not variations of the same task. They carry different consequences and should require different evidence, permissions and review. A single measure of model capability cannot settle the question.', 'A practical authority model distinguishes draft, recommend and act. The system may graduate between levels only when evaluation and live performance justify it. Tool access should be restricted to what each level requires, with a durable record of the evidence and approval behind material action.'] },
      { heading: 'Human oversight can become theatre', paragraphs: ['Adding an approval button does not guarantee meaningful control. If reviewers receive little context, face relentless volume or believe the system is usually correct, approval becomes a reflex. The human is present but the control is weak.', 'Good review design presents the original evidence, the proposed action and the reason the case requires attention. It routes higher-consequence work to people with the right authority and samples routine approvals for quality. Oversight must be measured by its effectiveness, not by the existence of a click.'] },
      { heading: 'Autonomy should be earned in small releases', paragraphs: ['The first release should operate on bounded volume with representative tests, explicit fallbacks and a route to a person. Teams should measure correct completion, corrections, rescue effort, incidents and the age of unresolved exceptions. Failures need classification by cause.', 'The best early system is rarely the most autonomous. It is the one colleagues can understand and improve. Greater autonomy is then a management decision supported by evidence, rather than the default ambition of the technology project.'] },
    ],
  },
  'cold-chain-collaboration': {
    title: 'Cold-chain data is useful only when it changes a decision',
    standfirst: 'Temperature-controlled operations already produce abundant readings. The harder problem is turning a material change into timely, accountable action while keeping the physical infrastructure and human evidence visible.',
    thesis: 'A credible cold-chain system must connect signal quality, operating context, response ownership and corrective evidence in one traceable case.',
    takeaways: [
      'Sensor data should be validated before operational severity is assessed.',
      'Exception quality matters more than alert volume.',
      'Monitoring should strengthen human responsibility and equipment controls rather than obscure them.',
    ],
    sections: [
      { heading: 'A reading is not yet an operational fact', paragraphs: ['A temperature value acquires meaning through context. Duration, asset state, product, location and recent activity can turn the same reading into a routine loading event, a maintenance concern or an urgent product risk. Systems that ignore this context create noise rather than intelligence.', 'Signal quality comes first. Missing heartbeats, implausible jumps and uncertain calibration should be treated as data exceptions. A system that quietly fills gaps or presents weak telemetry with false precision makes the operating risk harder to see.'] },
      { heading: 'Exception design is the centre of the service', paragraphs: ['Routine reports consume time, but material exceptions require judgement. An exception-led workflow can group related readings, attach equipment context and show the policy that caused escalation. This gives the reviewer a case rather than another isolated alert.', 'Precision matters because high alert volume changes behaviour. When teams learn that most alerts are not actionable, acknowledgement becomes mechanical and response slows. The system should be judged by whether it focuses attention on material cases without hiding uncertainty.'] },
      { heading: 'The software cannot be separated from the equipment', paragraphs: ['Monitoring depends on sensors, gateways, connectivity, calibration and maintenance. Discovery must therefore document the physical and network architecture as carefully as the interface. A sophisticated model cannot repair an unreliable data path.', 'Security boundaries matter as well. Analytics should not create an unnecessary route back into operational equipment. Read-only integration, least privilege and a definitive asset record are architectural controls, not documentation exercises.'] },
      { heading: 'Closure needs more than acknowledgement', paragraphs: ['A case is not complete when somebody presses close. The record should include the decision, corrective action, supporting observation and evidence that conditions recovered. This is valuable for assurance, but also for operational learning.', 'Repeated cases may reveal failing equipment, weak procedures or an inappropriate threshold. When closure data is structured, management can distinguish isolated excursions from systemic patterns and direct maintenance effort accordingly.'] },
      { heading: 'The collaboration should progress through evidence', paragraphs: ['The sensible sequence is to establish asset and data truth, define the exception policy, build the accountable response workflow and then pilot it beside current practice. Historical replay can supplement live testing when material incidents are rare.', 'Success should be assessed through signal coverage, alert precision, response time, closure completeness and reporting effort. These measures test whether the system improves operational control. They do not imply that software replaces the operator, the hazard analysis or legal responsibility.'] },
    ],
  },
  'small-teams-ai-advantage': {
    title: 'The AI advantage of a smaller firm is managerial, not technical',
    standfirst: 'SMEs rarely possess the largest technology budgets or datasets. They may nevertheless move faster because operational knowledge, customer context and decision authority sit closer together. That advantage survives only if leadership concentrates its attention.',
    thesis: 'Short decision lines can produce faster AI learning, provided the firm chooses one material workflow and builds reusable operating capability around it.',
    takeaways: [
      'Proximity between users, decision-makers and builders reduces translation loss.',
      'Scarce management attention should be concentrated on a bounded workflow.',
      'A successful first release should leave reusable data, controls and evaluation capability.',
    ],
    sections: [
      { heading: 'Proximity is a genuine asset', paragraphs: ['In a smaller firm, the person who understands an awkward customer exception may sit close to the person who can change the process. Senior leaders can observe the same work and make a decision without several committees. This shortens the loop between evidence and action.', 'Large organisations possess advantages of scale, but often pay a coordination tax. Requirements cross functions, data ownership is fragmented and approval takes time. SMEs can compete through learning speed if their leaders remain close to the operating detail.'] },
      { heading: 'Focus is the scarce resource', paragraphs: ['The temptation is to distribute AI tools widely and call the result transformation. That creates activity but little shared capability. Prompts and personal practices proliferate while the organisation learns little about a complete workflow.', 'A stronger portfolio begins with one constraint that is frequent, material and measurable. Leadership should state what will not be pursued at the same time. Concentration allows the team to establish a baseline, observe exceptions and reach a credible release decision.'] },
      { heading: 'The working group needs decision rights', paragraphs: ['A compact delivery group should combine the process expert, user, data owner, sponsor and builder. Its value lies less in size than in authority. Questions about scope, records and operating policy need answers while evidence is fresh.', 'This arrangement also makes accountability visible. The sponsor owns the business result, the process owner owns the work, the data owner approves context and the technical owner maintains the service. AI does not dissolve these responsibilities.'] },
      { heading: 'A pilot should create institutional assets', paragraphs: ['The application is only one output. A strong pilot also produces representative evaluation cases, clearer data ownership, practical risk decisions, operating measures and colleagues who understand the new workflow. These assets reduce the cost of the next release.', 'Reusability prevents a series of disconnected experiments. Common patterns for access, logging, evaluation and review can become a lightweight platform. The firm then gains capability without imitating the bureaucracy of a large enterprise.'] },
      { heading: 'Speed needs gates, not ceremony', paragraphs: ['Responsible delivery need not mean lengthy governance. Each stage can end with a simple evidence threshold: select the use case, confirm the baseline, pass representative tests, demonstrate controlled live use and then decide whether to expand.', 'These gates protect speed because they expose weak assumptions early. The smaller firm retains its advantage when it can stop an unpromising idea quickly, learn from the evidence and move scarce attention to a better constraint.'] },
    ],
  },
  'measure-automation-value': {
    title: 'Automation value is easy to calculate and hard to realise',
    standfirst: 'Multiplying theoretical minutes saved by salary produces an attractive number and a weak business case. Credible value measurement begins with a counterfactual, includes exception effort and distinguishes released capacity from cash.',
    thesis: 'Automation should be judged through a transparent benefits ledger that connects operating change to financial consequence and records the confidence behind each claim.',
    takeaways: [
      'A representative baseline is more valuable than a precise-looking estimate.',
      'Capacity, cost, revenue, quality, service and risk are different benefit types.',
      'The business needs an explicit plan for converting released time into realised value.',
    ],
    sections: [
      { heading: 'Begin with what would have happened anyway', paragraphs: ['Every business case implies a counterfactual. It compares the new process with the performance that would have occurred without investment. That comparison needs a representative period covering volume, cycle time, effort, quality and service.', 'A baseline built from one difficult week flatters the project. A baseline based solely on staff estimates creates false precision. Where operational data is weak, the uncertainty should be stated and measurement improved during discovery.'] },
      { heading: 'Minutes are not money', paragraphs: ['When automation removes task time, it creates capacity. The business realises cash only if cost is removed or avoided, or if the time is redeployed to work that produces measurable contribution. These outcomes require management action beyond the technical release.', 'A benefits ledger should therefore classify value. Capacity, cost, revenue, quality, service and risk each have different causal chains and evidence. Combining them into one headline saving makes the result larger and the decision less useful.'] },
      { heading: 'Gross saving ignores the new work', paragraphs: ['Automation adds review, exception handling, monitoring, supplier cost and support. It may shift routine effort away from many employees while increasing specialist work for a smaller group. The net result cannot be understood by measuring only the automated step.', 'Exception demand is especially important. A system may handle the majority of cases quickly and still destroy value if the remainder require lengthy rescue. Total operating effort should include the path from eligible input to accepted outcome.'] },
      { heading: 'Adoption should be measured against eligibility', paragraphs: ['Headline usage can conceal where people work around the system. The useful measure is the share of eligible work completed through the intended process, separated by team, task type and consequence. Reasons for reversion are diagnostic evidence.', 'Low adoption may indicate poor training, but it may also reveal weak fit, unreliable output or a workflow that makes review harder. Management should resist treating every adoption problem as employee resistance. Sometimes the product is wrong.'] },
      { heading: 'Benefits need an owner and a cadence', paragraphs: ['Each material benefit should have an operational owner, a definition and a review date. Finance can challenge the conversion to financial value, but the process owner must explain the operating change. Confidence should rise only as stronger evidence accumulates.', 'A transparent case can justify investment despite uncertainty. It should present a range, identify the assumptions that matter and specify what the pilot must prove. The purpose of measurement is not to manufacture certainty. It is to improve the next decision.'] },
    ],
  },
};
